language: android

env:
  global:
    - secure: "mvqMCa7W2F41sphpAu/17rRHNTYOjQscEWJR7dD3YtvDAoGp2IvIA2D76u9SbTbMcUJxZDv0pVJwhtY1RTwRNbKKoHIPLzeTfV6Llp4MMzm/VHzSeWPEEHSmKSZZbRGtJLO8lRstPaPu3/XIswG5aHuvCax1Nf/kw8cNft1CXjWyJvK8GmN5dFGdd0eqrTcSZOZivxPBtZcbzTdH/fSWSFepA1NkbmMbNBTtk1R9gNXpTZmikaNDhdAHUkXa3tvV2MHCGCGhmunuwWweo3A5JYFW/eHb+ewx7CV0PMfVAQ1tVmrN1tY0oeZniijjrd4pFQWjfiGn94cBwc5oqRnAYnHNOGAqlGhLO0oFt/OPIzbLDxDpNj3XE7VNN6gZUDsFtHqG7aTX6LcPp+ByI1VLfZMmjBB3SXV1A2tvXfRGkOWK1O4XkABdy2Icm6xh22ytD69SVxLQBbShbFtyVSTZzqsdTmyzWNsYCs3wFKp5sczUBTVhsgwS6QuqTmlbf00tjYCrK00Z9gDGdlJDQGAKN0yQtXMZEEsOv9QSnP83iGAqzuc7qiwRckhvBQtHq+PMpKwopLunNvVBzHpq0HAGDn74SaXyzyM65qk2C4n2DxHK5IBLaEPxbhdvb59MQaNJQH5KS7Ezga8/816puBWyakhpw1W0JRT2FXcSa/qajmg="
    - secure: "YrQcE5aKzI+qClWMemiJYBN6DDsmsrSOvGLiyC4s/Vq6FTacFE7YwrrTpYetiTjAfWLU0uzfnvYNZdVmxCoPNI0B3K4YsknYVv4e18H5hTaO4roF41P6Md5D0X04OlVzBMQmKHqPdBRjFLKU26cQ19eodJzW3+861p2CPhj89clX8dNAQUXs8pMkdQg4UgGPpuN1QGFzDVzeljfXbH6M0d+XhNnw+eNvNCDY77KQuOjzFbaajHza/l4QpWyu8ftAyAwQCRY93ZmLzFaoSlK5/kirikvs6dlZK4/AUmav8E0U5E7p3gtWnuTye5qAzuBBrRr1mb/DAvUcdltDpOa3S0ViF0VJ2UK1FEClhFyMORrv+xNO8ITnovGCmlC0Z0Ibvt3LSuHm+e1agyYa1489PtzNCCS46jiRGut2I+YKzdI2ECfmTHk1IsawasrKWGg6BoYPNnJijbpqc/ph39tdqEk/nPYznQor1cB73F4CaOZgbI7J2WeFlBxxoIVBpQY8Zwhp0i9C4/EIMHbqI8PCU1Bd9p0+fYFV03ELc5KBgyxwZHB6WguYDseXeleBnZhemptbcSEP/qS3M1mI+GhwOOLXmDUBFiydFebgsz4Ulr81tJavjQ0tWluMuUYmJYYYTgoduasUW/q1Y6AyPHm/nP2V1hvdROEzwB8j/kMqalk="
    - secure: "uodCnPKnQjRpUWYPM8IJ/s7IhkSqQuQjduIerGIJyB1tHh1GKyZMGFLPidAGpBFi/QyyOLtSg67EJY14NeWNFl4gSnTv/YzM+n/1ODCwMVpsYKCXNKROqGbIWjaga0rgfAAuf1S7v2Yh/I+nB47PjT1227kt9UwgtcZCltUx9FtS9VmTvZDFmn54cjpg3fttexUQnq9z3KYt+4X8ODEPZBC4XVxziBsHhAlUchYL5YDhxDZZrfH2omYzJq/7hh1OW1LZFb2/TZbFitGX/sf1lgOjOq7ea2pE46DGDoXBhXdILa3ZsBgA9xHJsaadPfIZddj3UgP8Idcs3WXeUJe/qKgmkJad8JKj/mqRc98N7+Qgvc2DL++YpbMp2lmjEnEebZPa0pahpnbfb3Zh6aV1fSKMOY/fkpIsBEwRmFMaeJ6p6GjBHmiLKRRp6b8oh449NOV2tvrJz1BkLDl08n+YRmDW8pFpbazMd5M03ew1jMvEehlqY5kVVyzFBpYaSW0+kE7/U4kzeP3hI/jztY+8xRyXZpxyPGWps/kNAq1pYywXH2ayBEoRh63sjdpRufM+DE72kad6pHtfRuop7ccPxb2YeKw9cZFxh//UqBQh+BLOz6Mgef/qCOhl3R4zGpAL1tBCOcyOFAybA5rgzVCfL5SOS2D+vF72r+Ju8FB3UWU="

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

branches:
  only:
    - master

before_install:
    # https://stackoverflow.com/questions/52274229/travis-ci-android-28-licenses-have-not-been-accepted
    - yes | sdkmanager "platforms;android-28"
    - openssl aes-256-cbc -K $encrypted_2e4e4247709c_key -iv $encrypted_2e4e4247709c_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xvf secrets.tar
    - mv google-services.json app/google-services.json

before_script:
    - echo "FABRIC_API_KEY="$FABRIC_API_KEY >> local.properties

script:
  - ./gradlew assembleRelease

after_success:
  - ./gradlew uploadDeployGateRelease

deploy:
  provider: script
  script: fastlane deploy
  on:
    branch: master
    tags: true
